version: "3"

services:
  pyspark:
    image: "jupyter/all-spark-notebook"
    volumes:
      - ./data_processing/notebooks:/home/jovyan/work/notebooks
      - ./data_processing/utils:/home/jovyan/work/utils
      - ./shared-secrets:/shared-secrets
    ports:
      - 8888:8888
    environment:
      - PYSPARK_SUBMIT_ARGS=--packages org.apache.hadoop:hadoop-aws:3.3.1,com.amazonaws:aws-java-sdk-bundle:1.11.100 pyspark-shell
      - VAULT_ADDR=http://vault:8200
    command: start-notebook.sh --NotebookApp.token=''
    networks:
      - vault-network

networks:
  vault-network:
